name: nervox

channels:
  - conda-forge
  - nvidia

dependencies:
  - python=3.12
  - ffmpeg
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - tensorflow[and-cuda]
    - tensorflow-datasets
