name: nervox

channels:
  - conda-forge
  - nvidia

dependencies:
  - python=3.10
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - ffmpeg
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - tensorflow==2.11.0
    - tensorflow-datasets
    - tensorflow-addons
