name: "Evaluate Diff"
description: "Check for Python file format changes and count hunks"

runs:
  using: "composite"
  steps:
    - name: "Evaluate Diff"
      id: evaluate_diff
      run: ./evaluate_diff.sh
      shell: bash

outputs:
  files:
    description: "List of Python files changed in the diff"
    value: ${{ steps.evaluate_diff.outputs.files }}
  hunks:
    description: "Number of hunks in the diff"
    value: ${{ steps.evaluate_diff.outputs.hunks }}
