name: "Evaluate Diff"
description: "Check for Python file format changes and count hunks"

runs:
  using: "composite"
  steps:
    - name: "Evaluate Diff"
      id: evaluate_diff
      run: |
        set -euxo pipefail
        # Capture output values from the shell script (example for bash)
        files=$(git diff --name-only | grep -E '.*\.py$')
        hunks=$(git diff --unified=0 | grep -c '^@@')

        # debug output
        echo "files=$files"
        echo "hunks=$hunks"
        
        echo "files=$files" >> $GITHUB_OUTPUT
        echo "hunks=$hunks_changed" >> $GITHUB_OUTPUT

      shell: bash

outputs:
  files:
    description: "List of Python files changed in the diff"
    value: ${{ steps.evaluate_diff.outputs.files }}
  hunks:
    description: "Number of hunks in the diff"
    value: ${{ steps.evaluate_diff.outputs.hunks }}
