name: "Evaluate Diff"
description: "Check for Python file format changes and count hunks"

runs:
  using: "composite"
  steps:
    - name: "Evaluate Diff"
      id: evaluate_diff
      run: |
        # Run the shell script
        ./evaluate_diff.sh

        # Capture output values from the shell script (example for bash)
        python_changes=$(grep -c '.py' <<< "$(git diff --name-only)")
        hunks=$(git diff --unified=0 | grep -c '^@@')

        # Set the output for further steps to use
        echo "python_changes=$python_changes" >> $GITHUB_OUTPUT
        echo "hunks=$hunks" >> $GITHUB_OUTPUT
      shell: bash

outputs:
  python_changes:
    description: "Whether Python file format changes were detected"
    value: ${{ steps.evaluate_diff.outputs.python_changes }}
  hunks:
    description: "Number of hunks in the diff"
    value: ${{ steps.evaluate_diff.outputs.hunks }}
