name: Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write


jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff

      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Setup Black
        uses:  psf/black@stable
        id: action_black
        with:
          options: "src pursuits"

      - name: Formating Suggestions [Black]
        run: |
          set -euxo pipefail
          TMPFILE=$(mktemp)
          git diff > "$TMPFILE"
          reviewdog -f=diff\
                    -name=BLACK\
                    -reporter=github-pr-review\
                    -level=warning\
                    -filter-mode=nofilter\
                    < "$TMPFILE"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_PR_REVIEW }}


