name: Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write


jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          bundler-cache: true


      - name: Run Black
        uses:  psf/black@stable
        id: action_black
        with:
          options: "--check ."
        continue-on-error: true 


      - uses: MeilCli/danger-action@v6
        with:
          danger_file: "Dangerfile"
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      


      # - name: Suggest Formating Changes
      #   uses: reviewdog/action-suggester@v1.18
      #   with:
      #     tool_name: BLACK
      #     github_token:  ${{ secrets.GITHUB_TOKEN }}
      #     filter_mode: "nofilter"
      #     fail_on_error: 'true'
      #     level: 'error'


      # - name: Run Bandit
      #   uses: microsoft/action-python@0.7.3
      #   with:
      #     workdir: .
      #     python_version: '3.12'
      #     bandit: true

      
      # - name: Run RUF
      #   uses: chartboost/ruff-action@v1
      #   with:
      #     args: ---fix -e
        
          
      # - name: Run Pyright
      #   uses: microsoft/action-python@0.7.3
      #   with:
      #     workdir: .
      #     python_version: '3.12'
      #     pyright: true


  # testing:
  #   runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
  #   strategy:
  #     matrix:
  #       python-version: ['3.9', '3.10', '3.11', '3.12']
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         cache: 'pip'
  #         cache-dependency-path: 'pyproject.toml'

  #     - name: Install Dependencies
  #       run: |
  #         python --version
  #         python -m pip install -e .[test]

  #     - name: Pytest
  #       uses: microsoft/action-python@0.7.3
  #       with:
  #         workdir: .
  #         python_version: ${{ matrix.python-version }}
  #         pytest: true
