name: Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, edited ]
  workflow_dispatch:


permissions: 
  contents: read
  pull-requests: write


jobs:
  Linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff

      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Setup Black
        uses:  psf/black@stable
        id: action_black
        with:
          options: ""
          src: "."

      - name: Check for Pyton File Changes
        id: diff_python
        run: ./.github/workflows/diff_python.sh

      - name: DEBUG
        run: |
          echo "Files: ${{ steps.diff_python.outputs.files_formatted }}"
          echo "Hunks: ${{ steps.diff_python.outputs.hunks }}"

      - name: Create Pull Request [Black]
        if: steps.diff_python.outputs.files_formatted && steps.diff_python.outputs.hunks >= 20
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ACTION_PULL_REQUEST }}
          title: "Format Python code with psf/black push"
          commit-message: ":art: Format Python code with psf/black"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/black

      - name: Create Suggestions within PR [Black]
        if: steps.diff_python.outputs.files_formatted && steps.diff_python.outputs.hunks < 20
        run: |
          echo "creating suggestions within PR.."

          
  security-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with: 
          exit_zero: true 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


